modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

issueTrackerURL="https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/issues" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/wither-skeleton-tweaks" #optional

authors="Shadows_of_Fire" #optional

license="MIT License" #mandatory

[[mods]] #mandatory

modId="wstweaks" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Wither Skeleton Tweaks" #mandatory

description='''
Tweaking wither skeletons for the better.
'''

[[dependencies.wstweaks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35.1.36,)" #mandatory
    ordering="NONE"
    side="BOTH"
	
[[dependencies.wstweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wstweaks]]
    modId="placebo"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"